-- 1. Create scripts table (if not exists)
CREATE TABLE IF NOT EXISTS public.scripts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  content TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert Initial Admin User (into app_users)
-- Only runs if admin doesn't exist
INSERT INTO public.app_users (username, password, name, role) 
SELECT 'admin', '1234', 'Admin MC', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.app_users WHERE username = 'admin');

-- 3. Update Policy for Scripts
ALTER TABLE public.scripts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Scripts" ON public.scripts;
CREATE POLICY "Public Access Scripts" ON public.scripts FOR ALL USING (true);

-- 4. Enable RLS for other tables just in case
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access App Users" ON public.app_users;
CREATE POLICY "Public Access App Users" ON public.app_users FOR ALL USING (true);
