-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'USER',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create clients table
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  company TEXT,
  total_spent NUMERIC DEFAULT 0,
  owner_id BIGINT REFERENCES public.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE,
  time TIME,
  location TEXT,
  type TEXT,
  status TEXT DEFAULT 'LEAD',
  price NUMERIC DEFAULT 0,
  paid NUMERIC DEFAULT 0,
  client TEXT,
  owner_id BIGINT REFERENCES public.users(id),
  checklist JSONB DEFAULT '[]'::jsonb,
  payments JSONB DEFAULT '[]'::jsonb,
  files JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create scripts table
CREATE TABLE IF NOT EXISTS public.scripts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  content TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Initial Data (Ignore if already exists)
INSERT INTO public.users (username, password, name, role) VALUES 
('admin', '1234', 'Admin MC', 'ADMIN'),
('user1', '1234', 'MC User 1', 'USER')
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.clients (name, phone, company, total_spent, owner_id) VALUES
('คุณสมศรี (K.Somsri)', '081-234-5678', 'Private Wedding', 45000, 1),
('บริษัท เทคคอร์ป จํากัด', '02-111-2222', 'Tech Corp', 120000, 1)
ON CONFLICT DO NOTHING; -- This might not work perfectly without unique constraint on name, but fine for initial setup

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scripts ENABLE ROW LEVEL SECURITY;

-- Policies (Drop before create to avoid error if exists)
DROP POLICY IF EXISTS "Public Access Users" ON public.users;
CREATE POLICY "Public Access Users" ON public.users FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Clients" ON public.clients;
CREATE POLICY "Public Access Clients" ON public.clients FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Events" ON public.events;
CREATE POLICY "Public Access Events" ON public.events FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Scripts" ON public.scripts;
CREATE POLICY "Public Access Scripts" ON public.scripts FOR ALL USING (true);
